# Generated by Django 4.0.1 on 2022-01-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='phone_number',
        ),
    ]
